version: '3.8'

services:
  expense_postgres:
    image: postgres:16
    container_name: expense_postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=expense_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - expense_postgres

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  expense-api:
    build:
      context: ..
      dockerfile: src/Services/Expense/Expense.API/Dockerfile
    container_name: expense_api
    restart: always
    ports:
      - "5130:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=expense_postgres;Database=expense_db;Username=postgres;Password=postgres
      - JwtSettings__SecretKey=IzometriBilisimIcinCokGizliVeUzunBirAnahtarKelime123!!
      - JwtSettings__Issuer=ExpenseAPI
      - JwtSettings__Audience=ExpenseAPI
    depends_on:
      - expense_postgres
      - rabbitmq

  notification-api:
    build:
      context: ..
      dockerfile: src/Services/Notification/ExpenseManagement.NotificationAPI/Dockerfile
    container_name: notification_api
    restart: always
    ports:
      - "5051:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMq__Host=rabbitmq
    depends_on:
      - rabbitmq
      - expense-api

volumes:
  pgdata: